stats on graphite metrics into kafka
criteo/graphite-writer-stats pull request #1
Opened 2019-09-23 08:07 UTC by melchiormoulin

2019-09-23 12:27 UTC, uepoch commented on .dockerignore
> +graphite-writer-stats
Isn't it the same as gitignore ?

2019-09-24 08:43 UTC, uepoch requested changes

2019-09-24 08:43 UTC, uepoch commented on .gitignore
> +.idea/
Add vscode files please

2019-09-24 08:43 UTC, uepoch commented on cmd/graphite-writer-stats/graphite-writer-stats.go
> +	"github.com/melchiormoulin/graphite-writer-stats/input"
fix imports

2019-09-24 08:43 UTC, uepoch commented on cmd/graphite-writer-stats/graphite-writer-stats.go
> +	flag.IntVar(&port, "port", 2112, "prometheus http endpoint port")
Is there a reason to chose that port ?

2019-09-24 08:43 UTC, uepoch commented on cmd/graphite-writer-stats/graphite-writer-stats.go
> +	flag.StringVar(&group, "group", "", "Kafka consumer group definition")
consumer group id ?

2019-09-24 08:43 UTC, uepoch commented on input/kafka.go
> +	"github.com/melchiormoulin/graphite-writer-stats/stats"
import

2019-09-24 08:43 UTC, uepoch commented on stats/processor_test.go
> +	if success {
Use github.com/stretchr/testify/assert

2019-09-24 08:43 UTC, uepoch commented on stats/processor.go
> +func Process(logger *zap.Logger, dataPoint []byte, componentsNb int) bool {
Make it returns an error

2019-09-24 08:43 UTC, uepoch commented on stats/processor.go
> +	process(logger, metricPath, componentsNb)
OPT: if you are privating the name of your public function, it should share the same behavior

2019-09-24 08:43 UTC, uepoch commented on stats/processor.go
> +	logger.Debug("metrics", zap.Any("metric", metric))
Since zap.Any use reflection, maybe check the level before calling it

2019-09-24 08:43 UTC, uepoch commented on cmd/graphite-writer-stats/graphite-writer-stats.go
> +func init() {
Please avoid using init when you can, you can put all this in the main function (and profit from having the logger initialized)

2019-09-24 08:43 UTC, uepoch commented on input/kafka.go
> +	ComponentsNb int
why public ?

2019-09-24 08:43 UTC, uepoch commented on input/kafka.go
> +func (kafka *Kafka) Close() {
This function should be renamed or (better) extract the signal logic in main instead

2019-09-24 08:43 UTC, uepoch commented on output/prometheus.go
> +		http.ListenAndServe(portBinding, nil)
you don't check the error here

2019-09-24 08:43 UTC, uepoch commented on stats/processor.go
> +		output.IncMetricPathErrorCounter(string(dataPoint))
The cardinality is WAY too high for this
you take the whole datapoint as a value

2019-09-24 08:43 UTC, uepoch commented on output/prometheus.go
> +}
You must reduce the cardinality by classifying errors

2019-09-24 08:43 UTC, uepoch commented on stats/identificator.go
> +func getApplicationType(components []string) ApplicationType {
This is very specific to criteo, it would make more sense to have this classification configurable via a config file instead

2019-09-24 08:43 UTC, uepoch commented on cmd/graphite-writer-stats/graphite-writer-stats.go
> +	brokers      = "localhost:9092"
You can just initialize your variables by flag.<Type> instead of flag.<Type>Var, they will get filled at flag.Parse() call

2019-09-24 08:43 UTC, uepoch commented on cmd/graphite-writer-stats/graphite-writer-stats.go
> +	brokers      = "localhost:9092"
It will avoid duplication

2019-09-24 08:43 UTC, uepoch commented on stats/processor.go
> +func extractMetricPath(metric []byte) (string, bool) {
this should check for valid metrics name and return an error to classify them in the error counters

OPT: Keep a track record of the last N "bad" metrics to help investigation to make them available, should we need them

2019-09-24 08:50 UTC, melchiormoulin commented on .dockerignore
> +graphite-writer-stats
nop

2019-09-24 08:52 UTC, melchiormoulin commented on cmd/graphite-writer-stats/graphite-writer-stats.go
> +	flag.IntVar(&port, "port", 2112, "prometheus http endpoint port")
just copy paste the example. Do you want an other one ?

2019-09-24 09:01 UTC, melchiormoulin commented on stats/processor.go
> +		output.IncMetricPathErrorCounter(string(dataPoint))
dont get it

2019-10-01 14:04 UTC, camathieu commented
Commit squash ?

2019-10-01 14:56 UTC, camathieu approved these changes

2019-10-01 14:56 UTC, camathieu commented on cmd/graphite-writer-stats/graphite-writer-stats.go
> +		logger.Panic("bad config rule.", zap.String("configFile", *config))
bad config ruleS / or bad rules file maybe ?

2019-10-01 14:56 UTC, camathieu commented on cmd/graphite-writer-stats/graphite-writer-stats.go
> +		logger.Panic("bad config rule.", zap.String("configFile", *config))
+ err

2019-10-01 14:57 UTC, merged